# Generated by Django 6.0.5 on 2026-06-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketreservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.JSONField(default=list),
        ),
    ]
