# Generated by Django 6.0.5 on 2026-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketreservation', '0002_booking_selected_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_details',
            field=models.JSONField(default=list),
        ),
    ]
