# Generated by Django 6.0.5 on 2026-07-07 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketreservation', '0003_booking_passenger_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['bus', 'status'], name='ticketreser_bus_id_009302_idx'),
        ),
    ]
